/**
 * Public gallery renderer.
 *
 * Turns the canonical portfolio document into the static HTML the public sees:
 * `art.html`, `tech.html`, a not-found page, and one canonical detail page per
 * published record. It performs no I/O — `scripts/build-portfolio.mjs` owns the
 * filesystem, validation and the public build.
 *
 * Two rules govern everything here:
 *
 * 1. Render from `publishedPortfolio(document)` only, so drafts, unusable
 *    images, unsafe destinations and authoring provenance cannot reach a page.
 * 2. Escape every string that comes out of that projection, except `id`,
 *    `slug`, `src`, `liveUrl` and `repositoryUrl`, which the content contract
 *    has already constrained. `escapeHtml` is attribute-safe, so `alt` — which
 *    is rendered inside an attribute — and every other free-text field can
 *    safely share one escaper.
 *
 * Design authority: docs/portfolio-design-brief.md and .tastemaker/style-lock.md.
 */

import { publishedPortfolio, detailPath } from './portfolio-content.mjs';

/** Stamped into every generated page so the build can recognise its own output. */
export const GENERATED_MARKER =
  '<!-- Generated by scripts/build-portfolio.mjs from content/portfolio.json. Do not edit by hand. -->';

/** Curated lists open with this many entries; the rest sit behind Show all. */
const CURATED_VISIBLE = 4;

/* ------------------------------------------------------------------ *
 * Escaping and small helpers
 * ------------------------------------------------------------------ */

const ESCAPES = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };

/**
 * Attribute-safe HTML escaping. Quotes are encoded as well as angle brackets,
 * so the same function is correct for element text and for attribute values
 * such as `alt`, where a bare `"` would otherwise break out of the attribute.
 */
export const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ESCAPES[character]);

const hasScheme = (url) => /^[a-z][a-z0-9+.-]*:/i.test(url);

/** Resolve a repo-relative asset or route against the page's own depth. */
const rebase = (url, prefix) => (hasScheme(url) ? url : `${prefix}${url}`);

/** `art/pieces/x/index.html` sits three directories down, so it needs `../../../`. */
const prefixFor = (path) => '../'.repeat(path.split('/').length - 1);

/** Shift a block of markup so the generated pages stay readable. */
const indent = (block, spaces) =>
  block
    .split('\n')
    .map((line) => (line.trim() === '' ? '' : ' '.repeat(spaces) + line))
    .join('\n');

const lines = (...parts) => parts.filter((part) => part !== '' && part !== null && part !== undefined).join('\n');

const attribute = (name, value) =>
  value === undefined || value === null || value === '' ? '' : ` ${name}="${escapeHtml(value)}"`;

/** Split supplied prose into paragraphs. Blank lines separate; nothing is invented. */
const paragraphs = (text) =>
  String(text)
    .split(/\n{2,}/)
    .map((block) => block.trim())
    .filter((block) => block !== '')
    .map((block) => `<p>${escapeHtml(block)}</p>`)
    .join('\n');

const pieceCount = (project) => `${project.pieceIds.length} ${project.pieceIds.length === 1 ? 'piece' : 'pieces'}`;

/* ------------------------------------------------------------------ *
 * Images
 * ------------------------------------------------------------------ */

/**
 * One `<img>` with reserved dimensions, optional responsive candidates and an
 * explicit loading strategy. `alt` is author text and is always escaped.
 */
function imageTag(image, { prefix, className, eager, sizes }) {
  const src = rebase(image.src, prefix);
  // Candidates are keyed by width: a duplicate descriptor invalidates the entry.
  const byWidth = new Map();
  if (Array.isArray(image.sources)) {
    for (const source of image.sources) byWidth.set(source.width, rebase(source.src, prefix));
  }
  if (byWidth.size > 0) byWidth.set(image.width, src);
  const candidates = [...byWidth]
    .sort(([a], [b]) => a - b)
    .map(([width, candidate]) => `${candidate} ${width}w`);
  const responsive = candidates.length > 0 ? ` srcset="${candidates.join(', ')}"${attribute('sizes', sizes)}` : '';
  return (
    `<img class="${className}" src="${src}"${responsive} alt="${escapeHtml(image.alt)}" ` +
    `width="${image.width}" height="${image.height}" loading="${eager ? 'eager' : 'lazy'}" decoding="async">`
  );
}

/**
 * The image plus a quiet "Image unavailable" fallback. The frame holds the
 * reserved aspect ratio whether or not the file loads, so a failed image never
 * collapses the card or loses its title.
 */
function framedImage(image, { prefix, className, frameClass, eager = false, sizes = '', ratio = '', focal = false }) {
  const styles = [`aspect-ratio: ${ratio === '' ? `${image.width} / ${image.height}` : ratio}`];
  if (focal && image.focalPoint) {
    styles.push(`--focal-x: ${image.focalPoint.x * 100}%`, `--focal-y: ${image.focalPoint.y * 100}%`);
  }
  return (
    `<span class="${frameClass}" style="${styles.join('; ')}">` +
    imageTag(image, { prefix, className, eager, sizes }) +
    '<span class="image-fallback" aria-hidden="true">Image unavailable</span>' +
    '</span>'
  );
}

/* ------------------------------------------------------------------ *
 * Cards
 * ------------------------------------------------------------------ */

const ART_SIZES = '(min-width: 1100px) 640px, (min-width: 700px) 46vw, 94vw';
const TECH_SIZES = '(min-width: 1100px) 380px, (min-width: 700px) 46vw, 94vw';
const DETAIL_SIZES = '(min-width: 1100px) 900px, 94vw';

/**
 * One card: image, title and quiet metadata inside a single link whose
 * accessible name identifies its destination. No nested links or buttons.
 */
function card({
  href,
  label,
  title,
  kind = '',
  summary = '',
  meta = '',
  image,
  prefix,
  eager,
  sizes,
  frameClass,
  ratio = '',
  focal = false,
  overflow = false,
  styleIds = null,
  section = '',
  modifier,
}) {
  const body = [
    kind === '' ? '' : `<span class="card__kind">${escapeHtml(kind)}</span>`,
    `<span class="card__title">${escapeHtml(title)}</span>`,
    summary === '' ? '' : `<span class="card__summary">${escapeHtml(summary)}</span>`,
    meta === '' ? '' : `<span class="card__meta">${escapeHtml(meta)}</span>`,
  ].join('');

  return (
    `<article class="card card--${modifier}"${overflow ? ' data-overflow="true"' : ''}` +
    `${styleIds === null ? '' : attribute('data-style-ids', styleIds.join(' '))}>` +
    `<a class="card__link" href="${href}" aria-label="${escapeHtml(label)}" data-detail-link` +
    `${attribute('data-return-section', section)}>` +
    framedImage(image, { prefix, className: 'card__image', frameClass, eager, sizes, ratio, focal }) +
    `<span class="card__body">${body}</span>` +
    '</a></article>'
  );
}

const artPieceCard = (piece, context) =>
  card({
    href: `${context.prefix}${detailPath('piece', piece.slug)}`,
    label: `${piece.title} — art piece`,
    title: piece.title,
    kind: context.kind ?? '',
    meta: [piece.year, piece.medium].filter(Boolean).join(' · '),
    image: piece.image,
    prefix: context.prefix,
    eager: context.eager,
    sizes: ART_SIZES,
    // An art piece keeps its own aspect ratio, which the inline style already
    // sets; no extra frame class is emitted, because none would style anything.
    frameClass: 'card__frame',
    overflow: context.overflow,
    styleIds: context.styleIds ?? null,
    section: context.section,
    modifier: 'piece',
  });

const artProjectCard = (project, context) =>
  card({
    href: `${context.prefix}${detailPath('art-project', project.slug)}`,
    label: `${project.title} — art project, ${pieceCount(project)}`,
    title: project.title,
    kind: context.kind ?? '',
    meta: [pieceCount(project), project.year].filter(Boolean).join(' · '),
    image: project.cover,
    prefix: context.prefix,
    eager: context.eager,
    sizes: ART_SIZES,
    frameClass: 'card__frame card__frame--cover',
    ratio: '4 / 3',
    overflow: context.overflow,
    section: context.section,
    modifier: 'project',
  });

const techProjectCard = (project, context) =>
  card({
    href: `${context.prefix}${detailPath('tech-project', project.slug)}`,
    label: `${project.title} — tech project`,
    title: project.title,
    summary: project.summary,
    meta: [project.role, project.year].filter(Boolean).join(' · '),
    image: project.cover,
    prefix: context.prefix,
    eager: context.eager,
    sizes: TECH_SIZES,
    frameClass: 'card__frame card__frame--cover card__frame--focal',
    ratio: '4 / 3',
    focal: true,
    overflow: context.overflow,
    section: context.section,
    modifier: 'tech',
  });

/* ------------------------------------------------------------------ *
 * Shared page chrome
 * ------------------------------------------------------------------ */

/**
 * The owner's way in. `?edit=1` is a bookmark from the retired drag overlay, so
 * it still works, but it now leads to the structured content editor rather than
 * loading an editing surface onto a public page. No admin module is imported
 * here: a visitor without the query string loads nothing extra, and the editor
 * it redirects to checks for a session before it shows anything.
 */
const editHookScript = (prefix, page) => `<script>
  if (new URLSearchParams(location.search).get("edit") === "1") {
    location.replace(new URL("${prefix}admin/content/?page=${page}", location.href));
  }
</script>`;

/** The global navigation shared by Tech, the detail views and the 404 page. */
function siteNav(prefix, current) {
  const link = (href, text, key) =>
    `    <li><a href="${prefix}${href}"${key === current ? ' class="current" aria-current="page"' : ''}>${text}</a></li>`;
  return lines(
    '<nav class="site-nav" id="top" aria-label="Site">',
    '  <div class="wrap">',
    `    <a href="${prefix}index.html" class="wordmark" aria-label="Jason — portfolio home"><img class="brand-logo" src="${prefix}assets/bard.svg" alt="" width="40" height="40">JASON</a>`,
    '    <ul class="nav-links">',
    indent(link('index.html', 'Home', 'home'), 2),
    indent(link('art.html', 'Art', 'art'), 2),
    indent(link('tech.html', 'Tech', 'tech'), 2),
    '    </ul>',
    '  </div>',
    '</nav>',
  );
}

const BACK_TO_TOP = '<footer class="gallery-footer"><a class="gallery-footer__top" href="#top">Back to top</a></footer>';

const emptyState = (message) => `<p class="empty-state">${escapeHtml(message)}</p>`;

const section = ({ id, heading, level = 'h2', pageTitle = false, body, extra = '' }) =>
  lines(
    `<section class="section" id="${id}" aria-labelledby="${id}-title">`,
    indent(
      `<${level} class="section__title${pageTitle ? ' section__title--page' : ''}" id="${id}-title">${escapeHtml(heading)}</${level}>`,
      2,
    ),
    extra === '' ? '' : indent(extra, 2),
    indent(body, 2),
    '</section>',
  );

const grid = (id, modifier, cards) =>
  lines(`<div class="grid grid--${modifier}" id="${id}">`, ...cards.map((markup) => indent(markup, 2)), '</div>');

/** The expansion control for a curated list. Hidden until JavaScript reveals it. */
const expandControl = (gridId, label) =>
  `<button type="button" class="control expand" data-expand="${gridId}" aria-controls="${gridId}" aria-expanded="false" hidden>${escapeHtml(label)}</button>`;

function page({ path, title, description, bodyClass, returnPage = '', canonical = false, editHook = false, body }) {
  const prefix = prefixFor(path);
  // A page is canonical at its own address, and a return query is never part of
  // it: `art.html?edit=1` and `art.html` are the same document.
  const canonicalHref = path.slice(path.lastIndexOf('/') + 1);
  // `lines` drops empty parts, so the final newline is appended rather than
  // passed in; every generated file ends with exactly one.
  return `${lines(
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="UTF-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
    `  <title>${escapeHtml(title)}</title>`,
    `  <meta name="description" content="${escapeHtml(description)}">`,
    canonical ? `  <link rel="canonical" href="${canonicalHref}">` : '',
    `  <link rel="stylesheet" href="${prefix}styles.css">`,
    `  <link rel="stylesheet" href="${prefix}gallery.css">`,
    '</head>',
    `<body class="${bodyClass}"${attribute('data-return-page', returnPage)}>`,
    `  ${GENERATED_MARKER}`,
    '  <a class="skip-link" href="#main">Skip to content</a>',
    indent(body, 2),
    `  <script type="module" src="${prefix}gallery.js"></script>`,
    editHook ? indent(editHookScript(prefix, canonicalHref), 2) : '',
    '</body>',
    '</html>',
  )}\n`;
}

/* ------------------------------------------------------------------ *
 * Art gallery page
 * ------------------------------------------------------------------ */

function renderArtPage(view) {
  const prefix = '';
  const projectsById = new Map(view.artProjects.map((project) => [project.id, project]));
  const piecesById = new Map(view.artPieces.map((piece) => [piece.id, piece]));

  const hasProjects = view.artProjects.length > 0;
  const hasPieces = view.artPieces.length > 0;

  // Only the first image on the page is the primary visible one.
  let eagerUsed = false;
  const nextEager = () => {
    if (eagerUsed) return false;
    eagerUsed = true;
    return true;
  };

  /* Selected Works shows the favorite records themselves, in curated order. */
  const favoriteCards = view.artFavorites
    .map((entry, index) => {
      const context = { prefix, overflow: index >= CURATED_VISIBLE, section: 'selected-works' };
      if (entry.type === 'piece') {
        const piece = piecesById.get(entry.id);
        return piece === undefined ? null : artPieceCard(piece, { ...context, kind: 'Piece', eager: nextEager() });
      }
      const project = projectsById.get(entry.id);
      return project === undefined ? null : artProjectCard(project, { ...context, kind: 'Project', eager: nextEager() });
    })
    .filter((markup) => markup !== null);

  const hasImages = favoriteCards.length > 0 || hasProjects || hasPieces;
  const colorToggle = hasImages
    ? '<button type="button" class="control color-toggle" data-color-toggle aria-pressed="false" hidden>Show original colors</button>'
    : '';

  const sections = [
    section({
      id: 'selected-works',
      heading: 'Selected Works',
      level: 'h1',
      pageTitle: true,
      extra: colorToggle,
      body:
        favoriteCards.length === 0
          ? emptyState('Work will appear here soon.')
          : lines(
              grid('selected-works-grid', 'selected', favoriteCards),
              favoriteCards.length > CURATED_VISIBLE ? expandControl('selected-works-grid', 'Show all selected works') : '',
            ),
    }),
  ];

  if (hasProjects) {
    const cards = view.artProjects.map((project) =>
      artProjectCard(project, { prefix, eager: nextEager(), overflow: false, section: 'projects' }),
    );
    sections.push(section({ id: 'projects', heading: 'Projects', body: grid('projects-grid', 'projects', cards) }));
  }

  if (hasPieces) {
    // Filter controls appear only when Jason has defined real styles; with none
    // defined the section is already the All view and ships no dead control.
    const filters =
      view.styles.length === 0
        ? ''
        : lines(
            '<div class="filters" role="group" aria-label="Filter by style" data-filters="explore-grid" hidden>',
            '  <button type="button" class="control filter" data-style="all" aria-pressed="true">All</button>',
            ...view.styles.map(
              (style) =>
                `  <button type="button" class="control filter" data-style="${escapeHtml(style.id)}" aria-pressed="false">${escapeHtml(style.name)}</button>`,
            ),
            '</div>',
          );

    const cards = view.artPieces.map((piece) =>
      artPieceCard(piece, {
        prefix,
        eager: nextEager(),
        overflow: false,
        section: 'explore',
        styleIds: piece.styleIds,
      }),
    );

    sections.push(
      section({
        id: 'explore',
        heading: 'Explore by Style',
        // The status region exists only alongside the controls it reports on.
        extra: lines(filters, filters === '' ? '' : '<p class="filter-status" role="status" data-filter-status="explore-grid"></p>'),
        body: grid('explore-grid', 'explore', cards),
      }),
    );
  }

  sections.push(
    section({
      id: 'about',
      heading: 'About Me',
      body:
        view.about.trim() === ''
          ? emptyState('A short biography will appear here soon.')
          : lines('<div class="prose">', indent(paragraphs(view.about), 2), '</div>'),
    }),
    section({
      id: 'contact',
      heading: 'Contact',
      body:
        view.contacts.length === 0
          ? emptyState('Contact details will appear here soon.')
          : lines(
              '<ul class="contact-list">',
              // `contact.url` is not one of the pre-constrained fields, so it is
              // escaped like any other authored string rather than relying on
              // `safeUrl` normalisation upstream.
              ...view.contacts.map(
                (contact) => `  <li><a href="${escapeHtml(contact.url)}">${escapeHtml(contact.label)}</a></li>`,
              ),
              '</ul>',
            ),
    }),
  );

  // The requested rail order is kept; a link is dropped only with its section.
  const railLinks = [
    hasProjects ? '<li><a href="#projects">Projects</a></li>' : '',
    hasPieces ? '<li><a href="#explore">Styles</a></li>' : '',
    '<li><a href="#selected-works" aria-label="Home — Art selected works">Home</a></li>',
    '<li><a href="#about">About Me</a></li>',
    '<li><a href="#contact">Contact</a></li>',
  ];

  const body = lines(
    '<div class="art-shell">',
    '  <header class="art-rail" id="top">',
    '    <a href="index.html" class="wordmark art-rail__brand" aria-label="Jason — portfolio home"><img class="brand-logo" src="assets/bard.svg" alt="" width="40" height="40">JASON</a>',
    '    <nav class="art-rail__nav" aria-label="Art sections">',
    '      <ul>',
    indent(lines(...railLinks), 8),
    '      </ul>',
    '    </nav>',
    '    <nav class="art-rail__switch" aria-label="Other portfolios">',
    '      <ul><li><a href="tech.html">Tech</a></li></ul>',
    '    </nav>',
    '  </header>',
    '  <div class="art-content">',
    '    <main id="main">',
    indent(lines(...sections), 6),
    '    </main>',
    `    ${BACK_TO_TOP}`,
    '  </div>',
    '</div>',
  );

  return page({
    path: 'art.html',
    title: 'Selected Works — Art — Jason',
    description: 'Jason’s art portfolio: selected works, projects, and pieces to explore by style.',
    bodyClass: 'gallery-page gallery-page--art art patterned',
    returnPage: 'art',
    canonical: true,
    editHook: true,
    body,
  });
}

/* ------------------------------------------------------------------ *
 * Tech gallery page
 * ------------------------------------------------------------------ */

function renderTechPage(view) {
  const prefix = '';
  const byId = new Map(view.techProjects.map((project) => [project.id, project]));
  const starred = view.techStarred.map((entry) => byId.get(entry.id)).filter(Boolean);
  const hasProjects = view.techProjects.length > 0;

  let eagerUsed = false;
  const nextEager = () => {
    if (eagerUsed) return false;
    eagerUsed = true;
    return true;
  };

  const sections = [];

  if (starred.length > 0) {
    const cards = starred.map((project, index) =>
      techProjectCard(project, { prefix, eager: nextEager(), overflow: index >= CURATED_VISIBLE, section: 'starred' }),
    );
    sections.push(
      section({
        id: 'starred',
        heading: 'Starred Projects',
        body: lines(
          grid('starred-grid', 'starred', cards),
          cards.length > CURATED_VISIBLE ? expandControl('starred-grid', 'Show all starred projects') : '',
        ),
      }),
    );
  }

  if (hasProjects) {
    const cards = view.techProjects.map((project) =>
      techProjectCard(project, { prefix, eager: nextEager(), overflow: false, section: 'projects' }),
    );
    sections.push(section({ id: 'projects', heading: 'Projects', body: grid('projects-grid', 'projects', cards) }));
  }

  const anchors = [
    starred.length > 0 ? '<li><a href="#starred">Starred Projects</a></li>' : '',
    hasProjects ? '<li><a href="#projects">Projects</a></li>' : '',
  ].filter((anchor) => anchor !== '');

  const anchorNav =
    anchors.length === 0
      ? ''
      : lines('<nav class="anchor-nav" aria-label="Tech sections">', '  <ul>', indent(lines(...anchors), 4), '  </ul>', '</nav>');

  const body = lines(
    siteNav(prefix, 'tech'),
    '<main id="main" class="tech-main">',
    '  <header class="page-head">',
    '    <h1 class="section__title section__title--page">Tech</h1>',
    '    <p class="page-head__intro">Jason’s published software projects.</p>',
    anchorNav === '' ? '' : indent(anchorNav, 4),
    '  </header>',
    indent(sections.length === 0 ? emptyState('Work will appear here soon.') : lines(...sections), 2),
    '</main>',
    BACK_TO_TOP,
  );

  return page({
    path: 'tech.html',
    title: 'Tech — Jason',
    description: 'Jason’s published software projects.',
    bodyClass: 'gallery-page gallery-page--tech tech',
    returnPage: 'tech',
    canonical: true,
    editHook: true,
    body,
  });
}

/* ------------------------------------------------------------------ *
 * Detail pages
 * ------------------------------------------------------------------ */

const backLink = (href, label) => `<a class="back-link" href="${href}" data-back-link>${escapeHtml(label)}</a>`;

const definition = (label, value) =>
  value === undefined || value === '' ? '' : `  <div class="meta__row"><dt>${label}</dt><dd>${escapeHtml(value)}</dd></div>`;

const definitionList = (rows) => {
  const present = rows.filter((row) => row !== '');
  return present.length === 0 ? '' : lines('<dl class="meta">', ...present, '</dl>');
};

const detailShell = (nav, back, article) =>
  lines(nav, '<main id="main" class="detail">', indent(back, 2), indent(article, 2), '</main>', BACK_TO_TOP);

function renderPieceDetail(piece, view) {
  const path = detailPath('piece', piece.slug);
  const prefix = prefixFor(path);
  const project = piece.projectId ? view.artProjects.find((entry) => entry.id === piece.projectId) : undefined;

  const article = lines(
    '<article class="detail__body detail--piece">',
    `  <h1 class="detail__title">${escapeHtml(piece.title)}</h1>`,
    indent(
      framedImage(piece.image, {
        prefix,
        className: 'detail__image',
        frameClass: 'detail__frame',
        eager: true,
        sizes: DETAIL_SIZES,
      }),
      2,
    ),
    indent(definitionList([definition('Year', piece.year), definition('Medium', piece.medium), definition('Dimensions', piece.dimensions)]), 2),
    piece.caption === undefined ? '' : indent(lines('<div class="prose">', indent(paragraphs(piece.caption), 2), '</div>'), 2),
    project === undefined
      ? ''
      : `  <p class="detail__project"><a href="${prefix}${detailPath('art-project', project.slug)}">In the project ${escapeHtml(project.title)}</a></p>`,
    '</article>',
  );

  return [
    path,
    page({
      path,
      title: `${piece.title} — Art — Jason`,
      description: piece.caption ?? piece.image.alt,
      bodyClass: 'gallery-page gallery-page--art art patterned',
      canonical: true,
      body: detailShell(siteNav(prefix, 'art'), backLink(`${prefix}art.html`, 'Back to Art'), article),
    }),
  ];
}

function renderArtProjectDetail(project, view) {
  const path = detailPath('art-project', project.slug);
  const prefix = prefixFor(path);
  const piecesById = new Map(view.artPieces.map((piece) => [piece.id, piece]));

  const gallery = project.pieceIds
    .map((pieceId) => piecesById.get(pieceId))
    .filter(Boolean)
    .map(
      (piece, index) =>
        `  <li class="collection__item"><a class="collection__link" href="${prefix}${detailPath('piece', piece.slug)}">` +
        framedImage(piece.image, {
          prefix,
          className: 'detail__image',
          frameClass: 'detail__frame',
          eager: index === 0,
          sizes: DETAIL_SIZES,
        }) +
        `<span class="collection__title">${escapeHtml(piece.title)}</span></a></li>`,
    );

  const article = lines(
    '<article class="detail__body detail--collection">',
    `  <h1 class="detail__title">${escapeHtml(project.title)}</h1>`,
    `  <p class="detail__count">${escapeHtml([pieceCount(project), project.year].filter(Boolean).join(' · '))}</p>`,
    project.summary === undefined ? '' : indent(lines('<div class="prose">', indent(paragraphs(project.summary), 2), '</div>'), 2),
    '  <ul class="collection">',
    indent(lines(...gallery), 2),
    '  </ul>',
    '</article>',
  );

  return [
    path,
    page({
      path,
      title: `${project.title} — Art — Jason`,
      description: project.summary ?? project.cover.alt,
      bodyClass: 'gallery-page gallery-page--art art patterned',
      canonical: true,
      body: detailShell(siteNav(prefix, 'art'), backLink(`${prefix}art.html#projects`, 'Back to Projects'), article),
    }),
  ];
}

function renderTechProjectDetail(project) {
  const path = detailPath('tech-project', project.slug);
  const prefix = prefixFor(path);

  const externalLinks = [
    project.liveUrl === undefined ? '' : `  <li><a href="${project.liveUrl}">Live site</a></li>`,
    project.repositoryUrl === undefined ? '' : `  <li><a href="${project.repositoryUrl}">Repository</a></li>`,
  ].filter((link) => link !== '');

  const caseStudy = project.sections.map((entry) =>
    lines(
      '<section class="detail__section">',
      `  <h2>${escapeHtml(entry.title)}</h2>`,
      indent(lines('<div class="prose">', indent(paragraphs(entry.body), 2), '</div>'), 2),
      '</section>',
    ),
  );

  const technologies =
    project.technologies.length === 0
      ? ''
      : lines(
          '<section class="detail__section">',
          '  <h2>Technologies</h2>',
          '  <ul class="tag-list">',
          ...project.technologies.map((technology) => `    <li>${escapeHtml(technology)}</li>`),
          '  </ul>',
          '</section>',
        );

  const screenshots =
    project.screenshots.length === 0
      ? ''
      : lines(
          '<section class="detail__section">',
          '  <h2>Screenshots</h2>',
          '  <ul class="collection">',
          ...project.screenshots.map(
            (shot) =>
              `    <li class="collection__item">${framedImage(shot, {
                prefix,
                className: 'detail__image',
                frameClass: 'detail__frame',
                sizes: DETAIL_SIZES,
              })}</li>`,
          ),
          '  </ul>',
          '</section>',
        );

  const article = lines(
    '<article class="detail__body detail--tech">',
    `  <h1 class="detail__title">${escapeHtml(project.title)}</h1>`,
    `  <p class="detail__summary">${escapeHtml(project.summary)}</p>`,
    indent(
      framedImage(project.cover, {
        prefix,
        className: 'detail__image',
        frameClass: 'detail__frame',
        eager: true,
        sizes: DETAIL_SIZES,
      }),
      2,
    ),
    indent(definitionList([definition('Role', project.role), definition('Year', project.year)]), 2),
    externalLinks.length === 0 ? '' : indent(lines('<ul class="link-list">', ...externalLinks, '</ul>'), 2),
    indent(lines(...caseStudy, technologies, screenshots), 2),
    '</article>',
  );

  return [
    path,
    page({
      path,
      title: `${project.title} — Tech — Jason`,
      description: project.summary,
      bodyClass: 'gallery-page gallery-page--tech tech',
      canonical: true,
      body: detailShell(siteNav(prefix, 'tech'), backLink(`${prefix}tech.html`, 'Back to Tech'), article),
    }),
  ];
}

/* ------------------------------------------------------------------ *
 * Not found
 * ------------------------------------------------------------------ */

function renderNotFound() {
  const article = lines(
    '<article class="detail__body">',
    '  <h1 class="detail__title">Page not found</h1>',
    '  <p class="detail__summary">That page is not here. It may have been unpublished, or the address may be wrong.</p>',
    '  <ul class="link-list">',
    '    <li><a href="art.html">Go to Art</a></li>',
    '    <li><a href="tech.html">Go to Tech</a></li>',
    '  </ul>',
    '</article>',
  );

  return page({
    path: '404.html',
    title: 'Page not found — Jason',
    description: 'That page is not here.',
    bodyClass: 'gallery-page gallery-page--notfound',
    body: lines(siteNav('', ''), '<main id="main" class="detail">', indent(article, 2), '</main>', BACK_TO_TOP),
  });
}

/* ------------------------------------------------------------------ *
 * Entry point
 * ------------------------------------------------------------------ */

/**
 * Render the whole public site.
 *
 * @param {object} document canonical portfolio document (drafts included)
 * @returns {Map<string, string>} relative path → HTML
 */
export function renderPortfolio(document) {
  const view = publishedPortfolio(document);
  const pages = new Map();

  pages.set('art.html', renderArtPage(view));
  pages.set('tech.html', renderTechPage(view));
  pages.set('404.html', renderNotFound());

  for (const piece of view.artPieces) {
    const [path, html] = renderPieceDetail(piece, view);
    pages.set(path, html);
  }
  for (const project of view.artProjects) {
    const [path, html] = renderArtProjectDetail(project, view);
    pages.set(path, html);
  }
  for (const project of view.techProjects) {
    const [path, html] = renderTechProjectDetail(project);
    pages.set(path, html);
  }

  return pages;
}
